### PR TITLE
Added Georgian localization

### PR DESCRIPTION
**Pull request by DraganRatkovich**
@jmdaweb Merge if possible.

### CODE REVIEW

**Comment by jmdaweb** [comment]
Hi,
I can't accept translations in this way, the translation workflow would be broken. Please, contact the NVDA georgian translation team and ask them to submit your work via srt.
@beqabeqa473 is included as part of the georgian team, so I'll mention him.
Closing pr.

**Comment by DraganRatkovich** [comment]
@jmdaweb Just wondering, are you using Crowdin for your add-on? If so, I can send from there.

**Comment by jmdaweb** [comment]
No, I'm using the official NVDA translation system. It consists of a Subversion repository with the translations, a server which performs certain tasks weekly, and this Git repository, which receives the results. I can accept code contributions via pull requests, but not translations. You can learn more [here](https://github.com/nvaccess/nvda/wiki/Translating) as well as in the other wiki pages related to translation.

**Comment by DraganRatkovich** [comment]
@jmdaweb Now it's clear, thanks.

**Comment by DraganRatkovich** [comment]
@jmdaweb I submitted the translation via SVN, hopefully it will show up here as well, or do you have to approve it first?

**Comment by jmdaweb** [comment]
I should receive it next friday.

**Comment by DraganRatkovich** [comment]
@jmdaweb Just wanting to quickly ask here, can I update the existing localization of your add-on for another language? There are outdated entries. I'll just delete the old .po and replace it, then I'll commit the new changes with SVN.

**Pull request closed without merging**
